export const HAND_CLICKED = "HAND_CLICKED";
export const HANDS_SELECTED = "HANDS_SELECTED";
// {
//   type: HAND_CLICKED, hand;
// }
export const CHECK_ANSWER = "CHECK_ANSWER";
export const RESET = "RESET";
export const LOAD_POSITION_SUCCESS = "LOAD_POSITION_SUCCESS";
export const LOAD_HAND_RANGES_SUCCESS = "LOAD_HAND_RANGES_SUCCESS";
export const LOAD_SCENARIOS_SUCCESS = "LOAD_SCENARIOS_SUCCESS";
export const SAVE_HAND_RANGE = "SAVE_HAND_RANGE";
export const SAVE_HAND_RANGE_SUCCESS = "SAVE_HAND_RANGE_SUCCESS";
export const POSITION_SELECTED_FOR_EDIT = "POSITION_SELECTED_FOR_EDIT";
export const MODE_CHANGED = "MODE_CHANGED";
export const SLIDER_MOVED = "SLIDER_MOVED";
export const SLIDER_MOVING = "SLIDER_MOVING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const SCENARIO_SELECTED = "SCENARIO_SELECTED";
export const POSITION_SET_TO_NULL = "POSITION_SET_TO_NULL";
export const LOAD_HYDRATED_SCENARIO_SUCCESS = "LOAD_HYDRATED_SCENARIO_SUCCESS";

export const IS_LOADING_HAND_RANGES = "IS_LOADING_HAND_RANGES";
export const IS_UPDATING_HAND_RANGES = "IS_UPDATING_HAND_RANGES";
